# not using sudo
sudo: false

language: node_js
node_js:
- 'lts/*'

# greenkeeper lock file
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

# main
script:
- yarn run lint
